package Interfaces;


import Controle.ControleSaisie;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import project.conectionProvider;
import static project.conectionProvider.connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hatem
 */
public class NewConsultation extends javax.swing.JFrame {

    /**
     * Creates new form NewConsulation
     */
    public NewConsultation() {
        initComponents();
        np.setVisible(false);
        np1.setVisible(false);
        nm.setVisible(false);
        nm1.setVisible(false);
        setTitle("Nouvelle consultation");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        envoyer = new javax.swing.JRadioButton();
        np = new javax.swing.JLabel();
        np1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        M = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        A = new javax.swing.JTextField();
        Ar = new javax.swing.JTextField();
        dc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nm = new javax.swing.JLabel();
        nm1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jRadioButton1.setText("Envoyer vers un specialiste");

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Ajouter Nouvelle consultation");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 12, -1, 38));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Patient ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 68, -1, -1));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 69, 138, -1));

        jLabel3.setText("Date du consultation :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 162, 1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Diagnostic :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 194, -1, -1));
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 183, 138, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 353, -1, 15));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 253, -1, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/menu-principal.png"))); // NOI18N
        jButton2.setText("Menu Principal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, -1, 60));

        envoyer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        envoyer.setForeground(java.awt.Color.white);
        envoyer.setText("Envoyer vers un spécialiste");
        envoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envoyerActionPerformed(evt);
            }
        });
        getContentPane().add(envoyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 74, -1, -1));

        np.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        np.setForeground(java.awt.Color.white);
        np.setText("Nom du spécialiste");
        getContentPane().add(np, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 128, -1, -1));
        getContentPane().add(np1, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 129, 128, -1));

        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/prescrip.png"))); // NOI18N
        jButton3.setText("Valider");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 161, 60));
        getContentPane().add(M, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 249, 138, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Medicament");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 248, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Analyse");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 303, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Acte Radio");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 369, -1, -1));
        getContentPane().add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 304, 138, -1));
        getContentPane().add(Ar, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 370, 138, -1));
        getContentPane().add(dc, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 129, 138, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Date du consultation:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 128, -1, -1));

        nm.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nm.setForeground(java.awt.Color.white);
        nm.setText("Nom du médecin");
        getContentPane().add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 183, -1, -1));
        getContentPane().add(nm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 184, 128, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel14.setForeground(java.awt.Color.red);
        jLabel14.setText("jj/mm/yyyy");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 80, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/image2.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new HOME().setVisible(true);//pour retourner à l'interface home
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Id=id.getText();
        String m=M.getText();
        String a=A.getText();
        String ar=Ar.getText();
        String Np=np1.getText();
        String Nm=nm1.getText();
        String Dc=dc.getText();
        String D=d.getText();

        try{
           connection = conectionProvider.getInstance().getConnection();

            Statement st = connection.createStatement();//Statement représente une instruction SQL
            ControleSaisie Cs=new ControleSaisie();
            if((!(Cs.ValidString(m)))||(!(Cs.ValidString(a)))||(!(Cs.dateValidation(Dc)))||(!(Cs.ValidString(ar)))){//verifier les données ecrit par l'utilisateur
                JOptionPane.showMessageDialog(null, "Formulaire invalide");
            }
            else{
                
                
            st.executeUpdate("insert into consultation values('"+Id+"','"+Dc+"','"+D+"') ");//permet l'insertion de consultaion dans la base de données
             st.executeUpdate("insert into prescription values('"+Id+"','"+m+"','"+a+"','"+ar+"') ");//permet l'insertion de prescription dans la base de données
            if(envoyer.isSelected()){
                if(!(Cs.ValidString(Np))||(!(Cs.ValidString(Nm))))
             JOptionPane.showMessageDialog(null, "nom du spécialiste ou nom du spécialité invalide");
                
                else{
                
            st.executeUpdate("insert into specialiste values('"+Id+"','"+Np+"','"+Nm+"') ");//permet l'insertion de specialite dans la base de données
                   JOptionPane.showMessageDialog(null, "Cette tache est bien effectue ");}
            }}

        }catch(SQLException ex)
        {

            JOptionPane.showMessageDialog(null,"Insertion invalide");

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void envoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envoyerActionPerformed
        // TODO add your handling code here:
        
        if(envoyer.isSelected())
        {
         np.setVisible(true);
        np1.setVisible(true);
        nm.setVisible(true);
        nm1.setVisible(true);
        }
        else{
        
         np.setVisible(false);
        np1.setVisible(false);
        nm.setVisible(false);
        nm1.setVisible(false);
        }
        
        
        
    }//GEN-LAST:event_envoyerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewConsultation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField Ar;
    private javax.swing.JTextField M;
    private javax.swing.JTextField d;
    private javax.swing.JTextField dc;
    private javax.swing.JRadioButton envoyer;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel nm;
    private javax.swing.JTextField nm1;
    private javax.swing.JLabel np;
    private javax.swing.JTextField np1;
    // End of variables declaration//GEN-END:variables
}
